###
GET http://localhost:3000/produtos

###
GET http://localhost:3000/produtos/1

###
POST http://localhost:3000/produtos
Content-Type: application/json

{
  "nome": "Notebook Gamer",
  "preco": 4999.90,
  "descricao": "RTX 4060",
  "estoque": 15,
  "categoria": "Informática",
  "marca": "Dell",
  "ativo": true
}

###

PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
  "nome": "Notebook Gamer DELL G15",
  "preco": 4999.90,
  "descricao": "RTX 3050",
  "estoque": 67,
  "categoria": "Informática",
  "marca": "Dell",
  "ativo": true
}

###

DELETE http://localhost:3000/produtos/4